application: webhic
version: 1
runtime: python
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: /admin/.*
  script: controllers/admin.py
  login: admin
  auth_fail_action: unauthorized

- url: /user/.*
  script: controllers/user.py
  login: required
  
- url: /forum/.*
  script: controllers/forum.py
  login: required

- url: /.*
  script: main.py